# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: katana
  name: katana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: katana
    spec:
      containers:
      - args:
        - --seed=69
        - --metrics=0.0.0.0:9100
        command:
        - katana
        image: ghcr.io/dojoengine/dojo:v0.5.0
        imagePullPolicy: IfNotPresent
        name: katana
        ports:
        - containerPort: 5050
          name: rpc
          protocol: TCP
        - containerPort: 9100
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: 250m
            memory: 2Gi
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      serviceAccount: default
      serviceAccountName: default

---
apiVersion: v1
kind: Service
metadata:
  name: katana
  labels:
    app: katana
spec:
  type: NodePort
  ports:
    - name: rpc
      port: 80
      protocol: TCP
      targetPort: 5050
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    app: katana