# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: torii
  name: torii
  namespace: external-nobody
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torii
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: torii
    spec:
      containers:
      - args:
        - --rpc=http://katana.external-nobody.svc.cluster.local
        - --world=0x46d71a62ab894b3bbe0bced1b872666dd707fb81e6fd7801b6abd82577391b2
        - --start-block=0
        - --metrics=0.0.0.0:9100
        command:
        - torii
        image: ghcr.io/dojoengine/dojo:v0.5.0
        imagePullPolicy: IfNotPresent
        name: torii
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9100
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      serviceAccount: default
      serviceAccountName: default

---
apiVersion: v1
kind: Service
metadata:
  name: torii
  labels:
    app: torii
  namespace: external-nobody
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    app: torii